databases:
  - name: rails6-test-app
    databaseName: rails6_test_app_production
    user: rails6_test_app

services:
  - type: web
    name: rails6-test-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails6-test-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
